name: LattePlugin
version: 1.0.0
main: io.github.chanemilia.lattePlugin.LattePlugin
api-version: 1.21

commands:
  lattereload:
    description: Reload the plugin configuration
    permission: latte.reload