name: LGPlugin
version: 1.1.0
main: io.github.chanemilia.LGPlugin.LGPlugin
api-version: 1.21
authors: [ChanEmilia]
description: SMP Management helper plugin.

commands:
  lgplugin:
    description: Main command for LGPlugin
    usage: /lgplugin <subcommand>
    permission: lg.op
    aliases: [lg]
